export const GAMES = {
  'modak-rush': {
    id: 'modak-rush',
    name: 'Modak Rush',
    icon: '🍬',
    image: '/games/modak-rush.png',
    description: 'Fast collection challenge',
    color: '#FF6B35',
    gradient: 'linear-gradient(135deg, #FF6B35, #ff8c42)',
    duration: 30,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Score',
    maxScore: 50000,
    route: '/game/modak-rush',
    leaderboardRoute: '/leaderboard',
  },
  'diya-dash': {
    id: 'diya-dash',
    name: 'Diya Dash',
    icon: '🪔',
    image: '/games/diya-dash.png',
    description: 'Memory & sequence challenge',
    color: '#FFB347',
    gradient: 'linear-gradient(135deg, #FFB347, #FF8C00)',
    duration: null,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Level',
    maxScore: 99999,
    route: '/game/diya-dash',
    leaderboardRoute: '/leaderboard',
  },
  'dhol-battle': {
    id: 'dhol-battle',
    name: 'Dhol Battle',
    icon: '🥁',
    image: '/games/dhol-battle.png',
    description: 'Rhythm challenge',
    color: '#E74C3C',
    gradient: 'linear-gradient(135deg, #E74C3C, #C0392B)',
    duration: 45,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Score',
    maxScore: 99999,
    route: '/game/dhol-battle',
    leaderboardRoute: '/leaderboard',
  },
  'rangoli-rush': {
    id: 'rangoli-rush',
    name: 'Rangoli Rush',
    icon: '🌸',
    image: '/games/rangoli-rush.png',
    description: 'Pattern puzzle',
    color: '#E91E9C',
    gradient: 'linear-gradient(135deg, #E91E9C, #9B59B6)',
    duration: null,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Score',
    maxScore: 99999,
    route: '/game/rangoli-rush',
    leaderboardRoute: '/leaderboard',
  },
  'mushak-maze': {
    id: 'mushak-maze',
    name: 'Mushak Maze',
    icon: '🐭',
    image: '/games/mushak-maze.png',
    description: 'Speed maze navigation',
    color: '#27AE60',
    gradient: 'linear-gradient(135deg, #27AE60, #2ECC71)',
    duration: null,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Score',
    maxScore: 99999,
    route: '/game/mushak-maze',
    leaderboardRoute: '/leaderboard',
  },
  'ganpati-logic': {
    id: 'ganpati-logic',
    name: 'Ganpati Logic',
    icon: '🧠',
    image: '/games/ganpati-logic.png',
    description: 'Brain blitz puzzles',
    color: '#8E44AD',
    gradient: 'linear-gradient(135deg, #8E44AD, #9B59B6)',
    duration: 45,
    soloSupported: true,
    multiplayerSupported: true,
    leaderboardMetric: 'Best Score',
    maxScore: 99999,
    route: '/game/ganpati-logic',
    leaderboardRoute: '/leaderboard',
  },
}

export const GAME_LIST = Object.values(GAMES)

export function getGame(id) {
  return GAMES[id] || null
}

export function getMultiplayerGames() {
  return GAME_LIST.filter(g => g.multiplayerSupported)
}
